#!/sw/comp/python/2.7.4/bin/python

import os
import sys
import click

from epigen import commands

cmd_dir = os.path.abspath( os.path.dirname( commands.__file__ ) )
class ComplexCLI( click.MultiCommand ):
    def list_commands(self, ctx):
        rv = []
        for filename in os.listdir( cmd_dir ):
            if filename.startswith( "cmd_" ) and filename.endswith( ".py" ):
                rv.append( filename[ 4:-3 ] )

        rv.sort( )

        return rv

    def get_command(self, ctx, name):
        try:
            if sys.version_info[ 0 ] == 2:
                name = name.encode( "ascii", "replace" )
            mod = __import__( "epigen.commands.cmd_" + name, None, None, [ "epigen" ] )
        except ImportError:
            return

        return mod.epigen

@click.command(no_args_is_help = True, cls = ComplexCLI)
def epigen():
    """Generate plink or phenotype data using an epistatic model."""

if __name__ == "__main__":
    epigen( )
